version: '3.3'

services:
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_EMAIL_TLS: "false"
      KEYCLOAK_EMAIL_HOST: mailhog
      KEYCLOAK_EMAIL_PORT: 1025
      KEYCLOAK_EMAIL_USERNAME: testuser
      KEYCLOAK_EMAIL_PASSWORD: testpassword
      KEYCLOAK_EMAIL_FROM: enowsinke@gmail.com
      KEYCLOAK_HTTPS_PORT: "8443"  # Specify the HTTPS port
      KEYCLOAK_HTTPS_KEYSTORE: /certs/keycloak.jks
      KEYCLOAK_HTTPS_KEYSTORE_PASSWORD: password
      KEYCLOAK_HTTPS_KEY_PASSWORD: password
    ports:
      - "8081:8080"
      - "8443:8443"  # Map the HTTPS port
    networks:
      - backend-network
    depends_on:
      - postgresql
      - localstack
      - mailhog
    volumes:
      - ./keycloak.crt:/certs/keycloak.crt
      - ./keycloak.key:/certs/keycloak.key
  # # Include other services as per your existing configuration
  # networks:
  #   backend-network:
  #     driver: bridge


  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - backend-network

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,iam
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend-network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: '4G'



  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
