version: '3.3'

services:
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_DATABASE_HOST: localhost  # Update to point to your LocalStack service
      KEYCLOAK_DATABASE_PORT: 5432      # Update port if necessary
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_EMAIL_TLS: "false"
      KEYCLOAK_EMAIL_HOST: mailhog
      KEYCLOAK_EMAIL_PORT: 1025
      KEYCLOAK_EMAIL_USERNAME: testuser
      KEYCLOAK_EMAIL_PASSWORD: testpassword
      KEYCLOAK_EMAIL_FROM: keycloak@example.com
    ports:
      - "8081:8080"
    networks:
      - backend-network
    depends_on:
      - postgresql
      - mailhog

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - backend-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend-network

networks:
  backend-network:
