version: '3.3'

services:
  keycloak:
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      
      # Add environment variable to enable logging of generated password
      # KEYCLOAK_LOGLEVEL: DEBUG  # Set log level to DEBUG

      # KEYCLOAK_ADMIN_EVENTS_ENABLED: "true"  # Enable admin events
    ports:
      - "8081:8080"
    networks:
      - backend-network
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
